---
name: MarkdownLint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
    paths:
      - "**.md"

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
