---
name: MyPy Python check

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
    paths:
      - "**.py"
  pull_request:

jobs:
  webapp:
    name: MyPy check webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jpetrucciani/mypy-check@master
        with:
          path: "webapp/"
          mypy_flags: "--config-file .mypy.ini"
          requirements_file: "webapp/requirements.txt"
